apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::482854218041:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-p77jRGOgraSh
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::482854218041:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-23T18:48:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1424"
  uid: b9c6f11c-3784-4415-b3f6-a600e932b317
